In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('diabetes.csv')

In [3]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [5]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [6]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [7]:
df.corr()['Outcome']

Pregnancies                 0.221898
Glucose                     0.466581
BloodPressure               0.065068
SkinThickness               0.074752
Insulin                     0.130548
BMI                         0.292695
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
Name: Outcome, dtype: float64

In [8]:
#make a small model

X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [9]:
X

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [10]:
y

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0])

In [11]:
# we do standardization of the data
from sklearn.preprocessing import StandardScaler
scalar = StandardScaler()

In [12]:
X = scalar.fit_transform(X)

In [15]:
X.shape

(768, 8)

In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [17]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [21]:
model = Sequential()

model.add(Dense(32, activation='relu', input_dim=8))
model.add(Dense(1, activation='sigmoid'))

c:\Users\Sanjog Bhalla\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [22]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [25]:
model.fit(X_train,y_train, epochs=100, batch_size=32, validation_data=(X_test,y_test))

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7866 - loss: 0.4431 - val_accuracy: 0.7727 - val_loss: 0.4984
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7883 - loss: 0.4412 - val_accuracy: 0.7727 - val_loss: 0.4990
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7866 - loss: 0.4399 - val_accuracy: 0.7662 - val_loss: 0.5003
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7915 - loss: 0.4388 - val_accuracy: 0.7727 - val_loss: 0.5004
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7899 - loss: 0.4378 - val_accuracy: 0.7662 - val_loss: 0.5015
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7915 - loss: 0.4362 - val_accuracy: 0.7597 - val_loss: 0.5023
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7932 - loss: 0.4349 - val_accuracy: 0.7727 - val_loss: 0.5040
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7915 - loss: 0.4339 - val_accuracy: 0.7662 - val_loss: 0.5050
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7915 - loss: 0.4329 - val_accuracy: 0.7662 - val_loss: 0.5033
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7948 - loss: 0.4318 - val_accuracy: 0.7727 - val_loss: 0.5020
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7948 - loss: 0.4319 - val_accuracy: 0.7727 - val_loss: 0.5035
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7915 - loss: 0.4306 - val_accuracy: 0.7727 - val_loss: 0.5050
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7899 - loss: 0.4293 - val_accuracy: 0.7727 - val_loss: 0.5061
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7948 - loss: 0.4282 - val_accuracy: 0.7727 - val_loss: 0.5052
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7883 - loss: 0.4278 - val_accuracy: 0.7727 - val_loss: 0.5056
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7964 - loss: 0.4268 - val_accuracy: 0.7727 - val_loss: 0.5067
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.7948 - loss: 0.4267 - val_accuracy: 0.7727 - val_loss: 0.5078
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7915 - loss: 0.4253 - val_accuracy: 0.7727 - val_loss: 0.5075
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7899 - loss: 0.4247 - val_accuracy: 0.7727 - val_loss: 0.5074
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7948 - loss: 0.4238 - val_accuracy: 0.7727 - val_loss: 0.5066
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7932 - loss: 0.4234 - val_accuracy: 0.7727 - val_loss: 0.5085
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7883 - loss: 0.4229 - val_accuracy: 0.7727 - val_loss: 0.5095
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7915 - loss: 0.4215 - val_accuracy: 0.7727 - val_loss: 0.5085
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7932 - loss: 0.4211 - val_accuracy: 0.7727 - val_loss: 0.5104
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7899 - loss: 0.4208 - val_accuracy: 0.7727 - val_loss: 0.5129
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7948 - loss: 0.4197 - val_accuracy: 0.7727 - val_loss: 0.5121
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7883 - loss: 0.4191 - val_accuracy: 0.7727 - val_loss: 0.5127
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7948 - loss: 0.4189 - val_accuracy: 0.7727 - val_loss: 0.5143
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7915 - loss: 0.4181 - val_accuracy: 0.7727 - val_loss: 0.5146
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7915 - loss: 0.4171 - val_accuracy: 0.7727 - val_loss: 0.5142
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7915 - loss: 0.4170 - val_accuracy: 0.7727 - val_loss: 0.5146
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4166 - val_accuracy: 0.7727 - val_loss: 0.5154
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7915 - loss: 0.4162 - val_accuracy: 0.7727 - val_loss: 0.5153
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7964 - loss: 0.4153 - val_accuracy: 0.7727 - val_loss: 0.5150
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7932 - loss: 0.4149 - val_accuracy: 0.7727 - val_loss: 0.5150
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7932 - loss: 0.4147 - val_accuracy: 0.7727 - val_loss: 0.5148
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7980 - loss: 0.4139 - val_accuracy: 0.7727 - val_loss: 0.5160
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7997 - loss: 0.4131 - val_accuracy: 0.7662 - val_loss: 0.5157
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7980 - loss: 0.4131 - val_accuracy: 0.7727 - val_loss: 0.5138
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7964 - loss: 0.4126 - val_accuracy: 0.7662 - val_loss: 0.5140
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7964 - loss: 0.4116 - val_accuracy: 0.7662 - val_loss: 0.5136
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7997 - loss: 0.4116 - val_accuracy: 0.7662 - val_loss: 0.5134
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7964 - loss: 0.4114 - val_accuracy: 0.7662 - val_loss: 0.5120
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8013 - loss: 0.4105 - val_accuracy: 0.7662 - val_loss: 0.5151
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - accuracy: 0.7997 - loss: 0.4099 - val_accuracy: 0.7662 - val_loss: 0.5158
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8013 - loss: 0.4103 - val_accuracy: 0.7727 - val_loss: 0.5151
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.8029 - loss: 0.4092 - val_accuracy: 0.7662 - val_loss: 0.5165
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.7980 - loss: 0.4091 - val_accuracy: 0.7662 - val_loss: 0.5162
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8013 - loss: 0.4087 - val_accuracy: 0.7662 - val_loss: 0.5140
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8029 - loss: 0.4085 - val_accuracy: 0.7662 - val_loss: 0.5142
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8046 - loss: 0.4077 - val_accuracy: 0.7662 - val_loss: 0.5149
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8013 - loss: 0.4077 - val_accuracy: 0.7662 - val_loss: 0.5162
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7997 - loss: 0.4066 - val_accuracy: 0.7727 - val_loss: 0.5168
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7997 - loss: 0.4063 - val_accuracy: 0.7727 - val_loss: 0.5188
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7932 - loss: 0.4065 - val_accuracy: 0.7727 - val_loss: 0.5191
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.7997 - loss: 0.4053 - val_accuracy: 0.7727 - val_loss: 0.5192
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8062 - loss: 0.4050 - val_accuracy: 0.7662 - val_loss: 0.5192
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7997 - loss: 0.4047 - val_accuracy: 0.7727 - val_loss: 0.5184
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8013 - loss: 0.4043 - val_accuracy: 0.7727 - val_loss: 0.5164
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7964 - loss: 0.4049 - val_accuracy: 0.7662 - val_loss: 0.5144
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7964 - loss: 0.4034 - val_accuracy: 0.7727 - val_loss: 0.5165
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7997 - loss: 0.4029 - val_accuracy: 0.7727 - val_loss: 0.5180
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8013 - loss: 0.4033 - val_accuracy: 0.7727 - val_loss: 0.5201
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8046 - loss: 0.4032 - val_accuracy: 0.7792 - val_loss: 0.5165
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8029 - loss: 0.4026 - val_accuracy: 0.7727 - val_loss: 0.5188
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8078 - loss: 0.4016 - val_accuracy: 0.7727 - val_loss: 0.5178
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7964 - loss: 0.4025 - val_accuracy: 0.7792 - val_loss: 0.5193
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - accuracy: 0.7948 - loss: 0.4016 - val_accuracy: 0.7792 - val_loss: 0.5191
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8046 - loss: 0.4003 - val_accuracy: 0.7727 - val_loss: 0.5211
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8094 - loss: 0.4000 - val_accuracy: 0.7727 - val_loss: 0.5215
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8094 - loss: 0.4001 - val_accuracy: 0.7662 - val_loss: 0.5238
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8078 - loss: 0.4003 - val_accuracy: 0.7662 - val_loss: 0.5214
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8062 - loss: 0.3997 - val_accuracy: 0.7662 - val_loss: 0.5229
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8078 - loss: 0.3991 - val_accuracy: 0.7532 - val_loss: 0.5246
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8062 - loss: 0.3990 - val_accuracy: 0.7532 - val_loss: 0.5241
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8078 - loss: 0.3982 - val_accuracy: 0.7662 - val_loss: 0.5216
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8062 - loss: 0.3983 - val_accuracy: 0.7597 - val_loss: 0.5188
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8111 - loss: 0.3980 - val_accuracy: 0.7662 - val_loss: 0.5199
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8127 - loss: 0.3975 - val_accuracy: 0.7597 - val_loss: 0.5219
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8111 - loss: 0.3968 - val_accuracy: 0.7662 - val_loss: 0.5194
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8078 - loss: 0.3964 - val_accuracy: 0.7662 - val_loss: 0.5222
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8078 - loss: 0.3966 - val_accuracy: 0.7597 - val_loss: 0.5230
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8046 - loss: 0.3969 - val_accuracy: 0.7727 - val_loss: 0.5222
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8094 - loss: 0.3954 - val_accuracy: 0.7662 - val_loss: 0.5232
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8078 - loss: 0.3953 - val_accuracy: 0.7597 - val_loss: 0.5250
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8094 - loss: 0.3953 - val_accuracy: 0.7597 - val_loss: 0.5222
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8127 - loss: 0.3945 - val_accuracy: 0.7597 - val_loss: 0.5214
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8111 - loss: 0.3942 - val_accuracy: 0.7597 - val_loss: 0.5227
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8127 - loss: 0.3945 - val_accuracy: 0.7468 - val_loss: 0.5243
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8160 - loss: 0.3939 - val_accuracy: 0.7532 - val_loss: 0.5226
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8143 - loss: 0.3933 - val_accuracy: 0.7532 - val_loss: 0.5245
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8143 - loss: 0.3933 - val_accuracy: 0.7468 - val_loss: 0.5274
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.8160 - loss: 0.3931 - val_accuracy: 0.7468 - val_loss: 0.5253
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8176 - loss: 0.3926 - val_accuracy: 0.7468 - val_loss: 0.5246
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8176 - loss: 0.3927 - val_accuracy: 0.7468 - val_loss: 0.5238
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8143 - loss: 0.3918 - val_accuracy: 0.7597 - val_loss: 0.5227
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8127 - loss: 0.3915 - val_accuracy: 0.7597 - val_loss: 0.5217
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8176 - loss: 0.3914 - val_accuracy: 0.7532 - val_loss: 0.5225
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8143 - loss: 0.3910 - val_accuracy: 0.7532 - val_loss: 0.5221
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8143 - loss: 0.3906 - val_accuracy: 0.7532 - val_loss: 0.5221

In [26]:
# 1. how to select appropriate optimizer
# 2. No of nodes in the hidden layer
# 3. how to select number of hidden layer
# 4. All in all one model

In [27]:
!pip install -U keras-tuner

Collecting keras-tuner
  Downloading keras_tuner-1.4.8-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: keras in c:\users\sanjog bhalla\anaconda3\lib\site-packages (from keras-tuner) (3.13.1)
Requirement already satisfied: packaging in c:\users\sanjog bhalla\anaconda3\lib\site-packages (from keras-tuner) (24.2)
Requirement already satisfied: requests in c:\users\sanjog bhalla\anaconda3\lib\site-packages (from keras-tuner) (2.32.3)
Collecting kt-legacy (from keras-tuner)
  Downloading kt_legacy-1.0.5-py3-none-any.whl.metadata (221 bytes)
Requirement already satisfied: grpcio in c:\users\sanjog bhalla\anaconda3\lib\site-packages (from keras-tuner) (1.76.0)
Requirement already satisfied: protobuf in c:\users\sanjog bhalla\anaconda3\lib\site-packages (from keras-tuner) (5.29.3)
Requirement already satisfied: typing-extensions~=4.12 in c:\users\sanjog bhalla\anaconda3\lib\site-packages (from grpcio->keras-tuner) (4.15.0)
Requirement already satisfied: absl-py in c:\users\sanjog bhalla\anaconda3\lib\site-packages (from keras->keras-tuner) (2.3.1)
Requirement already satisfied: numpy in c:\users\sanjog bhalla\anaconda3\lib\site-packages (from keras->keras-tuner) (2.1.3)
Requirement already satisfied: rich in c:\users\sanjog bhalla\anaconda3\lib\site-packages (from keras->keras-tuner) (13.9.4)
Requirement already satisfied: namex in c:\users\sanjog bhalla\anaconda3\lib\site-packages (from keras->keras-tuner) (0.1.0)
Requirement already satisfied: h5py in c:\users\sanjog bhalla\anaconda3\lib\site-packages (from keras->keras-tuner) (3.12.1)
Requirement already satisfied: optree in c:\users\sanjog bhalla\anaconda3\lib\site-packages (from keras->keras-tuner) (0.18.0)
Requirement already satisfied: ml-dtypes in c:\users\sanjog bhalla\anaconda3\lib\site-packages (from keras->keras-tuner) (0.5.4)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\sanjog bhalla\anaconda3\lib\site-packages (from requests->keras-tuner) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\sanjog bhalla\anaconda3\lib\site-packages (from requests->keras-tuner) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\sanjog bhalla\anaconda3\lib\site-packages (from requests->keras-tuner) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\sanjog bhalla\anaconda3\lib\site-packages (from requests->keras-tuner) (2025.8.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\sanjog bhalla\anaconda3\lib\site-packages (from rich->keras->keras-tuner) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\sanjog bhalla\anaconda3\lib\site-packages (from rich->keras->keras-tuner) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\sanjog bhalla\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras->keras-tuner) (0.1.0)
Downloading keras_tuner-1.4.8-py3-none-any.whl (129 kB)
Downloading kt_legacy-1.0.5-py3-none-any.whl (9.6 kB)
Installing collected packages: kt-legacy, keras-tuner

   -------------------- ------------------- 1/2 [keras-tuner]
   -------------------- ------------------- 1/2 [keras-tuner]
   -------------------- ------------------- 1/2 [keras-tuner]
   -------------------- ------------------- 1/2 [keras-tuner]
   -------------------- ------------------- 1/2 [keras-tuner]
   -------------------- ------------------- 1/2 [keras-tuner]
   ---------------------------------------- 2/2 [keras-tuner]

Successfully installed keras-tuner-1.4.8 kt-legacy-1.0.5

In [29]:
import keras_tuner as kt